name: deploy react app
on: push
jobs: 
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4
        
      - name: install npm packages
        run: npm install
        
      - name: npm run
        run: mpm run build
        
      - name: test npm
        run: npm run test
