name: deploy react app
on: push
permissions:
  contents: write  
jobs: 
  deploy-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app
        
      - name: Build the React app
        run: npm run build
        working-directory: ./my-app
        
      - name: Run tests
        run: npm test
        working-directory: ./my-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-app/build
