name: hello world
on: push
jobs: 
  print-information:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello World!"
      - name: print Registration no
        run: echo "22cb052"
      - name: print name
        run: echo "shankar"
